# -*- coding: utf-8 -*-
"""Texter1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13yz5qYRGdzlMtUHGxLxIteUzvQd4zYVx
"""

!pip install gradio langchain langchain-openai telebot

!pip install gradio langchain langchain-openai python-telegram-bot

import os
import gradio as gr
from langchain.prompts import PromptTemplate
from langchain_core.runnables import RunnableSequence
from langchain_openai import OpenAI
import telebot
import logging; logging.basicConfig(level=logging.DEBUG)
import requests

os.environ["OPENAI_API_KEY"]
os.environ["LANGCHAIN_API_KEY"] 
os.environ["BOT_TOKEN"]

BOT_TOKEN = os.environ["BOT_TOKEN"]
CHANNEL = "@Texter_Channel_test"
bot = telebot.TeleBot(os.environ["BOT_TOKEN"])

generations = 0
MAX_FREE = 5
PRODAMUS_LINK = "https://texterws.payform.ru"

template = """
Create a well-structured {text_type} from the provided Context.
The {text_type} should effectively capture the key points, insights, and information from the Context.
Focus on maintaining a coherent flow and using proper grammar and language.
Incorporate relevant headings, subheadings, and bullet points to organize the content.
Ensure that the tone of the {text_type} is {style} (e.g., formal/informal), engaging and informative, catering to {target_audience} audience, written by {role}.
Integrate the provided {keywords} naturally for SEO optimization, include a meta-description at the start, and end with a call to action suitable for {platform}.
Use this language: {language} (default: Russian).
Feel free to enhance the context by adding additional examples, explanations, and insights where necessary to make it unique and valuable.
The goal is to convert context into a polished, original written resource (length: {length} characters) on the topic {topic}, while maintaining accuracy and coherence. Avoid plagiarism by rephrasing in your own words.
CONTEXT: {text}
{text_type}:
"""

prompt = PromptTemplate(
    input_variables=["role", "target_audience", "platform", "text_type", "style", "keywords", "length", "topic", "text"],
    template=template,
)

llm = OpenAI(temperature=0.7)
chain = prompt | llm

def generate(role, target_audience, platform, text_type, style, keywords, length, topic, text):
    global generations
    if generations >= MAX_FREE:
        return f"Лимит 5 бесплатных/день исчерпан. Купите: {PRODAMUS_LINK}"
    max_limits = {
        ("Telegram", "пост"): 1000,
        ("Telegram", "статья"): 2000,
        ("Telegram", "longread"): 4000,
    }
    key = (platform, text_type)
    max_length = max_limits.get(key, 4000)
    if length > max_length:
        length = max_length
    input_data = {
        "role": role,
        "target_audience": target_audience,
        "platform": platform,
        "text_type": text_type,
        "style": style,
        "keywords": keywords,
        "length": length,
        "topic": topic,
        "text": text,
        "language": "Russian"
    }
    print("Input data:", input_data)
    try:
        result = chain.invoke(input_data)
    except Exception as e:
        print(f"API Error: {str(e)}")
        return f"Error: {str(e)}"
    generations += 1
    return result[:length]

def post_to_telegram(output):
    try:
        bot.send_message(CHANNEL, output)
        requests.post("https://hooks.zapier.com/hooks/catch/25132555/uivojo8/", json={"text": output})
        return "Опубликовано!"
    except Exception as e:
        return f"Ошибка: {str(e)}"

with gr.Blocks() as demo:
    gr.Markdown("### Samara Agent: Freemium (5 бесплатно/день)")
    role = gr.Dropdown(choices=["Маркетолог", "Блогер", "SMM-специалист", "Предприниматель", "Студент", "Инженер", "Журналист", "Писатель"], label="Роль автора")
    target_audience = gr.Dropdown(choices=["Потребители продуктов/услуг", "Студенты и обучающиеся", "Бизнес-профессионалы", "Родители", "Путешественники", "ЗОЖ-ники", "Техно энтузиасты", "Инвесторы", "Подростки", "Миллениалы", "Пожилые", "Женщины", "Мужчины", "Экологи энтузиасты", "Геймеры", "Кулинары и любители еды"], label="Целевая аудитория")
    platform = gr.Dropdown(choices=["Telegram", "ВКонтакте", "Яндекс.Дзен", "Instagram", "Facebook", "LinkedIn", "Pinterest", "Одноклассники", "Twitter (X)", "ЯRus", "TenChat", "CMS сайтов"], label="Платформа размещения")
    text_type = gr.Dropdown(choices=["пост", "статья", "longread"], label="Вид текста")
    style = gr.Dropdown(choices=["Сюжетный", "Описание", "Новостной", "Убеждающий", "Креативный", "Инженерный", "Доказательный", "Личный"], label="Стиль")
    keywords = gr.Textbox(label="Ключевые слова (через запятую)")
    length = gr.Slider(100, 8000, value=1000, label="Длина (знаков без пробелов)")
    topic = gr.Textbox(label="Тема")
    text = gr.Textbox(label="Контекст (текст для обработки)")
    output = gr.Textbox(label="Сгенерированный текст")
    gen_btn = gr.Button("Генерировать")
    post_btn = gr.Button("Опубликовать в Telegram")
    post_output = gr.Textbox(label="Статус публикации")
    gen_btn.click(generate, inputs=[role, target_audience, platform, text_type, style, keywords, length, topic, text], outputs=output)
    post_btn.click(post_to_telegram, inputs=output, outputs=post_output)

demo.launch()
import uvicorn
if __name__ == "main":
    uvicorn.run("app:demo", host="0.0.0.0", port=3000, reload=True)